"""add user preference columns in User

Revision ID: a375188e5f15
Revises: ff7603b2ccb9
Create Date: 2025-05-10 22:49:27.120973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a375188e5f15'
down_revision: Union[str, None] = 'ff7603b2ccb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferred_text_model', sa.String(), nullable=True))
    op.add_column('user', sa.Column('preferred_speech_model', sa.String(), nullable=True))
    op.add_column('user', sa.Column('preferred_transcribe_model', sa.String(), nullable=True))
    op.add_column('user', sa.Column('use_history', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('prompt_template', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferred_text_model')
    op.drop_column('user', 'preferred_speech_model')
    op.drop_column('user', 'preferred_transcribe_model')
    op.drop_column('user', 'use_history')
    op.drop_column('user', 'prompt_template')
    # ### end Alembic commands ###
