"""add otp columns in User

Revision ID: ff7603b2ccb9
Revises: 0bc0911de3cf
Create Date: 2025-05-08 16:11:34.345816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff7603b2ccb9'
down_revision: Union[str, None] = '0bc0911de3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_code')
    op.drop_column('user', 'otp_expires_at')
    # ### end Alembic commands ###
